spring.application.name=apihistorico

server.port=8082

spring.datasource.url=jdbc:postgresql://localhost:5432/incendio
spring.datasource.username=incendio
spring.datasource.password=123
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true